
const nodemailer = require("nodemailer");
const PDFDocument = require("pdfkit");

const sendPdfReceipt = async (data) => {
  return new Promise(async (resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 40 });
      const buffers = [];

      doc.on("data", buffers.push.bind(buffers));
      doc.on("error", reject);

      doc.on("end", async () => {
        try {
          const pdfBuffer = Buffer.concat(buffers);

          const transporter = nodemailer.createTransport({
            service: "gmail",
            auth: {
              user: process.env.EMAIL_USER,
              pass: process.env.EMAIL_PASS
            }
          });

          await transporter.sendMail({
            from: `"EduVault ERP" <${process.env.EMAIL_USER}>`,
            to: data.studentEmail,
            subject: "📄 Official Fee Receipt – EduVault",
            html: `
              <p>Hello <b>${data.studentName}</b>,</p>
             <p>Your payment has been received.</p>
             <p>Please find your official receipt attached.</p>
              <br>
              <p>Regards,<br><b>EduVault ERP</b></p>
            `,
            attachments: [
              {
                filename: `EduVault-Receipt-${data.paymentId}.pdf`,
                content: pdfBuffer,
                contentType: "application/pdf"
              }
            ]
          });

          console.log("📎 Fee receipt emailed successfully");
          resolve(true);
        } catch (mailErr) {
          console.error("❌ Email send failed:", mailErr);
          reject(mailErr);
        }
      });

      /* ================= COLORS ================= */
      const C = {
        navy: "#0f172a",
        gold: "#c9a227",
        gray: "#6b7280",
        border: "#e5e7eb",
        green: "#16a34a",
        white: "#ffffff"
      };

      /* ================= BORDER ================= */
      doc.rect(20, 20, 555, 802).lineWidth(3).stroke(C.navy);

      /* ================= HEADER ================= */
      doc.font("Helvetica-Bold").fontSize(22).fillColor(C.navy)
        .text("OFFICIAL FEE RECEIPT", { align: "center" });

      doc.moveDown(0.5);

      doc.fontSize(14).fillColor(C.gray)
        .text("EDUVAULT ACADEMIC ERP", { align: "center" });

      doc.fontSize(10).fillColor(C.gray)
        .text(`Receipt No: INV-${data.paymentId}`, 40, 120)
        .text(`Date: ${new Date().toLocaleDateString()}`, 420, 120);

      /* ================= WATERMARK ================= */
      doc.fontSize(60).fillColor("#f3f4f6")
        .rotate(-30, { origin: [300, 400] })
        .text("EDUVAULT", 120, 360)
        .rotate(30, { origin: [300, 400] });

      /* ================= STUDENT INFO ================= */
      doc.roundedRect(40, 160, 515, 90, 10).stroke(C.border);

      doc.fontSize(11).fillColor(C.navy)
        .text(`Student Name: ${data.studentName}`, 60, 175)
        .text(`Student ID: ${data.studentId}`, 60, 195)
        .text(`Fee Type: ${data.feeType}`, 60, 215)

        .text(`Email: ${data.studentEmail}`, 300, 175)
        .text(`Phone: ${data.studentPhone}`, 300, 195);

      /* ================= TABLE ================= */
      const tableY = 280;

      doc.font("Helvetica-Bold").fontSize(11).fillColor(C.navy)
        .text("DESCRIPTION", 50, tableY)
        .text("AMOUNT", 350, tableY)
        .text("STATUS", 460, tableY);

      doc.moveTo(40, tableY + 15).lineTo(555, tableY + 15).stroke();

      const y = tableY + 30;

      doc.font("Helvetica").fontSize(11).fillColor(C.navy)
        .text(`${data.feeType}`, 50, y)

        .text(`₹${data.amount}`, 350, y);

      doc.roundedRect(440, y - 4, 80, 20, 10).fill(C.green);

      doc.fillColor(C.white).fontSize(10)
        .text("PAID", 465, y + 2);

      /* ================= TOTAL ================= */
      doc.font("Helvetica-Bold").fontSize(14).fillColor(C.navy)
        .text("TOTAL AMOUNT PAID", 50, y + 60);

      doc.fontSize(20).fillColor(C.gold)
        .text(`₹${data.amount}`, 350, y + 58);

      doc.fontSize(10).fillColor(C.gray)
        .text(`Payment Method: ${data.paymentMethod}`, 50, y + 95);

      /* ================= FOOTER ================= */
      doc.fontSize(9).fillColor(C.gray)
        .text(
          "Generated by EduVault ERP • Digitally Verified • No Signature Required",
          40,
          780,
          { align: "center", width: 515 }
        );

      doc.end();

    } catch (err) {
      reject(err);
    }
  });
};

module.exports = sendPdfReceipt;
